name: LaGriT Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LaGriT build dependencies
      run: |
        sudo apt-get update -y && sudo apt-get upgrade -y 
        sudo apt-get install -y build-essential openssl vim gfortran cmake git \
        wget libz-dev m4 bison python3 python3-pip python3-setuptools \
        update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 && \
        update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - name: Build ExodusII
      run: make exodus
    - name: Build LaGriT
      run: make release WITH_EXODUS=0
    - name: Test LaGriT
      run: make test
    - name: Test PyLaGriT
      run: |
        python PyLaGriT/setup.py install
        python -c "from pylagrit import PyLaGriT; lg = PyLaGriT()"
