name: LaGriT Build Status

on: [push, pull_request]

jobs:
  build:
    #name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macOS-latest]
        #, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage
      - name: (Ubuntu) Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y \
            build-essential openssl gfortran cmake git \
            wget libz-dev m4 bison
        if: matrix.os == 'ubuntu-latest'
      - name: (macOS) Install build dependencies
        run: |
          brew reinstall cmake
          brew reinstall gcc
        if: matrix.os == 'macOS-latest'
      - name: Compile Exodus
        run: |
          mkdir -p ~/TPLs/build/
          mkdir -p ~/TPLs/install/
          EXO_BUILD_DIR=$HOME/TPLs/build/ \
          EXO_INSTALL_DIR=$HOME/TPLs/install/ \
          ./install-exodus.sh
      - name: Build/test LaGriT
        run: |
          mkdir build/ && mkdir install/ && cd build/
          cmake .. \
            -D LaGriT_BUILD_STATIC=ON \
            -D CMAKE_BUILD_TYPE=Debug \
            -D Exodus_ROOT=${EXO_INSTALL_DIR} \
            -D CMAKE_INSTALL_PREFIX=$(pwd)/../install/
          make && make install
      - name: Test PyLaGriT
        run: |
          echo "lagrit_exe : '$(pwd)/install/bin/lagrit'" >> ~/.pylagritrc
          cat ~/.pylagritrc
          cd PyLaGriT/
          python3 setup.py install
          python3 -c "from pylagrit import PyLaGriT; lg = PyLaGriT(); lg.sendline('cmo/status')"
      - name: Upload compiled LaGriT
        uses: actions/upload-artifact@v2.2.4
        with:
          name: lagrit-${{ matrix.os }}
          path: ./install/bin/lagrit
          if-no-files-found: error
          retention-days: 30
